version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: bellford
    ports:
      - "8887:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./script.js:/usr/share/nginx/html/script.js
      - ./style.css:/usr/share/nginx/html/style.css
